### ISSUE TITLE
chaincode upgrade failed 

### ISSUE THREAD

**Issue by bjwswang** [bestchains/fabric-operator#241]
chaincode status
```yaml
  - lastTransitionTime: "2023-04-14T10:50:25Z"
    message: chaincode is not running on this peer node bjwswang-peer-k3kp5
    nextStage: Running
    reason: chaincode is not running on this peer node bjwswang-peer-k3kp5
    status: "False"
    type: Error
  - lastTransitionTime: "2023-04-14T10:50:30Z"
    message: chaincode is running
    nextStage: ""
    reason: ""
    status: "True"
    type: Running
  phase: ChaincodeApproved
  sequence: 1
```
